"""Fetches job listings from curated, community-maintained GitHub repos.

These repos (SimplifyJobs and friends) publish a machine-readable
`listings.json` alongside their README tables, generated by bots that scrape
company career pages. We just consume that JSON.
"""
import json
import os
import time

import requests

CACHE_DIR = os.path.join(os.path.dirname(__file__), "cache")
CACHE_TTL_SECONDS = 60 * 60 * 6  # 6 hours

# Each source: (name, listing_type, raw URL to listings.json)
SOURCES = [
    (
        "Internships/Co-op (SimplifyJobs)",
        "internship",
        "https://raw.githubusercontent.com/SimplifyJobs/Summer2026-Internships/dev/.github/scripts/listings.json",
    ),
    (
        "New Grad (vanshb03)",
        "new_grad",
        "https://raw.githubusercontent.com/vanshb03/New-Grad-2026/dev/.github/scripts/listings.json",
    ),
]


def _cache_path(name):
    safe = "".join(c if c.isalnum() else "_" for c in name)
    return os.path.join(CACHE_DIR, f"{safe}.json")


def _fetch_one(name, listing_type, url, force_refresh=False):
    os.makedirs(CACHE_DIR, exist_ok=True)
    path = _cache_path(name)

    if not force_refresh and os.path.exists(path):
        age = time.time() - os.path.getmtime(path)
        if age < CACHE_TTL_SECONDS:
            with open(path) as f:
                return json.load(f)

    try:
        resp = requests.get(url, timeout=20)
        resp.raise_for_status()
        data = resp.json()
        with open(path, "w") as f:
            json.dump(data, f)
        return data
    except (requests.RequestException, ValueError):
        # Fall back to stale cache if the fetch fails
        if os.path.exists(path):
            with open(path) as f:
                return json.load(f)
        return []


def fetch_all_listings(force_refresh=False):
    """Returns a list of normalized job dicts from all curated sources."""
    jobs = []
    for name, listing_type, url in SOURCES:
        raw = _fetch_one(name, listing_type, url, force_refresh=force_refresh)
        for entry in raw:
            jobs.append(_normalize(entry, listing_type, name))
    return jobs


def _normalize(entry, listing_type, source_name):
    def _parse_date(val):
        """Return epoch seconds for a variety of date formats.

        Accepts:
        - numeric timestamps (int/float seconds since epoch)
        - ISO 8601 strings (e.g. 2026-05-01 or 2026-05-01T12:34:56Z)
        - None -> None
        """
        if val is None:
            return None
        # If it's already a number (seconds since epoch), return as float
        if isinstance(val, (int, float)):
            try:
                return float(val)
            except Exception:
                return None

        # Otherwise try parsing ISO-like strings
        try:
            # Attempt common ISO formats without external deps
            # Strip fractional seconds and timezone Z for simple parsing
            s = str(val).strip()
            # Handle plain date YYYY-MM-DD
            if len(s) == 10 and s[4] == "-" and s[7] == "-":
                t = time.strptime(s, "%Y-%m-%d")
                return time.mktime(t)

            # Try full datetime variants
            # Remove trailing Z
            if s.endswith("Z"):
                s = s[:-1]
            # Replace T with space if present
            s = s.replace("T", " ")
            # Try parsing common orders
            for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M"):
                try:
                    t = time.strptime(s, fmt)
                    return time.mktime(t)
                except Exception:
                    continue
        except Exception:
            pass

        return None

    return {
        "id": entry.get("id") or entry.get("url", ""),
        "title": entry.get("title", "Unknown role"),
        "company": entry.get("company_name", "Unknown company"),
        "category": entry.get("category", ""),
        "locations": entry.get("locations", []) or [],
        "url": entry.get("url", ""),
        "company_url": entry.get("company_url", ""),
        "active": bool(entry.get("active", False)),
        "terms": entry.get("terms", []) or [],
        "date_posted": _parse_date(entry.get("date_posted")),
        "date_updated": _parse_date(entry.get("date_updated")),
        "sponsorship": entry.get("sponsorship", ""),
        "degrees": entry.get("degrees", []) or [],
        "listing_type": listing_type,
        "source": source_name,
    }


def cache_status():
    """Returns metadata about when each source was last refreshed."""
    status = []
    for name, listing_type, url in SOURCES:
        path = _cache_path(name)
        if os.path.exists(path):
            mtime = os.path.getmtime(path)
            status.append({"name": name, "last_fetched": mtime, "cached": True})
        else:
            status.append({"name": name, "last_fetched": None, "cached": False})
    return status
